from pathlib import Path
import json,shutil
root=Path('atom/ports');up=Path('atom/vendor')
css='''*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#03050b;color:#fff;font:14px system-ui,sans-serif}canvas,#scene{display:block;width:100%;height:100%}.head{position:fixed;top:12px;left:14px;pointer-events:none;text-shadow:0 1px 5px #000}h1{font-size:20px;margin:0}p{font-size:11px;color:#b9c7d9;margin:5px 0}.controls{position:fixed;bottom:12px;left:12px;right:12px;display:flex;gap:6px}button{min-height:44px;flex:1;background:#111b30df;border:1px solid #45516b;color:#e9edfa;border-radius:7px;font:14px system-ui;padding:6px 8px}button.active{background:#eed4ac;color:#192137}.fps{position:fixed;right:14px;top:15px;font:11px monospace;color:#b9c7d9;pointer-events:none}button:focus-visible{outline:2px solid white}#failure{position:fixed;top:100px;left:20px;right:20px;background:#182034;padding:16px;display:none}'''
def index(body,scripts):return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style></head><body>'+body+'<span id="fps" class="fps">测量中</span><div id="failure"></div><script>window.addEventListener("error",function(e){var n=document.getElementById("failure");n.style.display="block";n.textContent="渲染失败："+e.message;});var frames=0,last=performance.now();function measure(t){frames++;if(t-last>1000){document.getElementById("fps").textContent=Math.round(frames*1000/(t-last))+" FPS";frames=0;last=t}requestAnimationFrame(measure)}requestAnimationFrame(measure);</script>'+scripts+'</body></html>'
p=root/'fluid-atlas';s=(up/'fluid/script.js').read_text();a=s.index('// Mobile promo section');b=s.index('// Simulation section');s=s[:a]+s[b:];s=s.replace('startGUI();','// ATOM controls replace upstream desktop GUI.');s=s.replace('DYE_RESOLUTION: 1024','DYE_RESOLUTION: 512').replace('PRESSURE_ITERATIONS: 20','PRESSURE_ITERATIONS: 12').replace('BLOOM_ITERATIONS: 8','BLOOM_ITERATIONS: 4').replace('SUNRAYS_RESOLUTION: 196','SUNRAYS_RESOLUTION: 128');s='function ga(){}\n'+s
(p/'script.js').write_text(s)
shutil.copy(up/'fluid/LDR_LLL1_0.png',p/'LDR_LLL1_0.png');shutil.copy(up/'fluid/LICENSE',p/'LICENSE')
(p/'controls.js').write_text('''document.getElementById('burst').onclick=function(){splatStack.push(12)};document.getElementById('pause').onclick=function(){config.PAUSED=!config.PAUSED;this.textContent=config.PAUSED?'继续':'暂停'};document.getElementById('quality').onclick=function(){config.DYE_RESOLUTION=config.DYE_RESOLUTION===512?256:512;initFramebuffers();this.textContent=config.DYE_RESOLUTION===512?'精细':'流畅'};document.getElementById('clear').onclick=function(){gl.clearColor(0,0,0,1);gl.bindFramebuffer(gl.FRAMEBUFFER,dye.read.fbo);gl.clear(gl.COLOR_BUFFER_BIT);gl.bindFramebuffer(gl.FRAMEBUFFER,dye.write.fbo);gl.clear(gl.COLOR_BUFFER_BIT)};''')
(p/'index.html').write_text(index('<canvas></canvas><div class="head"><h1>流体画布</h1><p>Pavel Dobryakov · 拖动注入彩色流体</p></div><div class="controls"><button id="burst">迸发</button><button id="pause">暂停</button><button id="quality">精细</button><button id="clear">清空</button></div>','<script src="script.js"></script><script src="controls.js"></script>'))
p=root/'planetarium';shutil.copy(up/'spacekit/build/spacekit.js',p/'spacekit.js');shutil.copy(up/'spacekit/LICENSE',p/'LICENSE');shutil.copytree(up/'spacekit/src/data',p/'data',dirs_exist_ok=True);shutil.copytree(up/'spacekit/src/assets',p/'assets',dirs_exist_ok=True)
for a,b in [('planet/eso_earth.jpg','earth.jpg'),('jupiter/jupiter2_4k.jpg','jupiter.jpg'),('saturn/th_saturn.png','saturn.png'),('saturn/saturn_rings_top.png','rings.png')]:shutil.copy(up/'spacekit/examples'/a,p/b)
(p/'main.js').write_text('''var base=new URL('.',location.href).href;var viz=new Spacekit.Simulation(document.getElementById('scene'),{basePath:base,jdPerSecond:.05,unitsPerAu:1,camera:{initialPosition:[0,-3.5,1.6]}});viz.createLight([-5,-5,4]);viz.createStars({minSize:.55});var radius=58232.503/149598000;var objects={earth:viz.createSphere('earth',{textureUrl:base+'earth.jpg',radius:1,atmosphere:{enable:true,color:0x4288d9,outerSizeRatio:.035},levelsOfDetail:[{radii:0,segments:48}]}),jupiter:viz.createSphere('jupiter',{textureUrl:base+'jupiter.jpg',radius:1,levelsOfDetail:[{radii:0,segments:48}]}),saturn:viz.createSphere('saturn',{textureUrl:base+'saturn.png',radius:radius,axialTilt:26.7,levelsOfDetail:[{radii:0,segments:48}]})};objects.saturn.addRings(74270.580913,140478.924731,base+'rings.png',96);var controls=viz.getViewer().get3jsCameraControls();controls.autoRotate=true;controls.autoRotateSpeed=.8;controls.enablePan=false;var names={earth:'地球 · 蓝色家园',jupiter:'木星 · 风暴巨人',saturn:'土星 · 冰尘之环'},current='earth';function select(id){current=id;Object.keys(objects).forEach(function(k){objects[k].get3jsObjects().forEach(function(o){o.visible=k===id})});viz.zoomToFit(objects[id],id==='saturn'?1.5:1.15).then(function(){controls.minDistance=id==='saturn'?radius*2.8:1.4;controls.maxDistance=id==='saturn'?radius*14:8;controls.update()});document.getElementById('title').textContent=names[id];document.querySelectorAll('[data-planet]').forEach(function(b){b.classList.toggle('active',b.dataset.planet===id)})}document.querySelectorAll('[data-planet]').forEach(function(b){b.onclick=function(){select(b.dataset.planet)}});document.getElementById('spin').onclick=function(){controls.autoRotate=!controls.autoRotate;this.textContent=controls.autoRotate?'暂停巡航':'自动巡航'};select('earth');window.addEventListener('pagehide',function(){viz.stop();viz.getRenderer().dispose()});''')
(p/'index.html').write_text(index('<div id="scene"></div><div class="head"><h1 id="title">正在加载天体…</h1><p>Spacekit · 拖动环绕 · 滚轮缩放</p></div><div class="controls"><button data-planet="earth" class="active">地球</button><button data-planet="jupiter">木星</button><button data-planet="saturn">土星</button><button id="spin">暂停巡航</button></div>','<script src="spacekit.js"></script><script src="main.js"></script>'))
for id,name,desc in [('fluid-atlas','流体画布','移植Pavel WebGL Fluid Simulation，GPU实时流体与染料模拟'),('planetarium','天体观测台','移植Spacekit，高清行星纹理、光照、大气和土星环')]:
 (root/id/'bundle.json').write_text(json.dumps(dict(manifest=dict(id=id,name=name,description=desc,entry='index.html',layout='fullscreen'),files={'index.html':(root/id/'index.html').read_text()}),ensure_ascii=False))
# Board-specific adaptations verified on ATOM's Mali-G52 / Chromium91.
p=root/'fluid-atlas'/'script.js'
s=p.read_text().replace('let image = new Image();','let image = new Image();\n    image.crossOrigin = "anonymous";').replace("supportLinearFiltering = gl.getExtension('OES_texture_float_linear');",'supportLinearFiltering = true; // WebGL2 RGBA16F linear filtering verified on Mali-G52.').replace('DENSITY_DISSIPATION: 1,','DENSITY_DISSIPATION: 0.3,').replace('c.r *= 0.15;','c.r *= 0.45;').replace('c.g *= 0.15;','c.g *= 0.45;').replace('c.b *= 0.15;','c.b *= 0.45;')
p.write_text(s)
p=root/'planetarium'/'main.js';s=p.read_text().replace('basePath:base,',"basePath:base.replace(/\/$/,''),").replace('function select(id){current=id;','function select(id){current=id;viz.getViewer().get3jsCamera().position.set(0,-3.5,2.7);controls.target.set(0,0,0);controls.update();').replace("id==='saturn'?1.5:1.15","id==='saturn'?0.45:0.65");p.write_text(s)
p=root/'planetarium'/'spacekit.js';p.write_text(p.read_text().replace('float radius = 0.0389259903;','float radius = 0.0003892599032072621; // ATOM Saturn shadow scale'))
for id in ['fluid-atlas','planetarium']:
 p=root/id/'index.html';p.write_text(p.read_text().replace('<script src=','<script crossorigin="anonymous" src='))
 b=json.loads((root/id/'bundle.json').read_text());b['files']['index.html']=p.read_text();(root/id/'bundle.json').write_text(json.dumps(b,ensure_ascii=False))
