"""Build ATOM math and CircuitJS wrappers around vendored upstream engines."""
from pathlib import Path
import json,shutil,hashlib
ROOT=Path(__file__).resolve().parents[1]
def finish(p,name,description,icon):
 svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">'+icon+'</svg>'
 (p/'icon.svg').write_text(svg)
 (p/'bundle.json').write_text(json.dumps({'manifest':{'id':p.name,'name':name,'description':description,'entry':'index.html','layout':'fullscreen','theme_ui':'controls','icon':'icon.svg'},'files':{'index.html':(p/'index.html').read_text(),'icon.svg':svg}},ensure_ascii=False,indent=2))
p=ROOT/'ports/math-playground';p.mkdir(exist_ok=True)
shutil.copy(ROOT/'vendor/cindy-source/LICENSE',p/'LICENSE')
(p/'UPSTREAM.txt').write_text('https://github.com/CindyJS/CindyJS\nEngine build f52f219b1f17269d569b46426b6cee57269e9aae (header of distributed Cindy.js)\nExamples referenced source a7dbbbaaa16c7d8c0aca04181ddf0f8f1744b754\nCindy.js and CindyGL.js downloaded from https://cindyjs.org/dist/latest/\n'+''.join(f'{x.name} sha256 {hashlib.sha256(x.read_bytes()).hexdigest()}\n' for x in [p/'Cindy.js',p/'CindyGL.js']))
(p/'index.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><title>数学游乐场</title><script crossorigin="anonymous" src="Cindy.js"></script><script crossorigin="anonymous" src="CindyGL.js"></script><style>html,body{margin:0;overflow:hidden;height:100%;font:13px sans-serif;background:var(--bg);color:var(--ink)}.head{position:absolute;top:10px;left:12px;right:12px;display:flex;justify-content:space-between}#scene{position:absolute;top:36px;left:0;width:100%;height:272px}#scene canvas{width:100%;height:100%}.atomtools{position:absolute;bottom:8px;left:10px;right:10px;display:flex;gap:6px}.atomtools button{height:38px;flex:1;font-size:13px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--ink)}#hint{font-size:11px;color:var(--muted)}</style></head><body><div class="head"><span>数学游乐场</span><span id="hint">拖动橙色点，改变分形</span></div><div id="scene"></div><div class="atomtools"><button data-mode="julia">复数分形</button><button data-mode="rays">光线包络</button><button data-mode="triangle">三角几何</button><button id="reset">重置</button></div><script src="main.js"></script></body></html>''')
(p/'main.js').write_text('''var cdy,mode='julia';
var scenes={julia:{rect:[-2.4,-1.5,2.4,1.5],geometry:[{name:'C',type:'Free',pos:[-.72,.2],color:[1,.6,.2],size:9}],init:'use("CindyGL");n=36;f(z,c):=z*z+c;iter(z,c):=(escaped=0;repeat(n,if(abs(z)<4,z=f(z,c);escaped=escaped+1));if(escaped==n,(.025,.035,.06),hue(escaped/n+.58)*(0.4+0.6*escaped/n)));',draw:'c=complex(C);colorplot(iter(complex(#),c));draw(C,color->(1,.7,.2),size->9);'},
rays:{rect:[-8,-5,8,5],geometry:[{name:'A',type:'Free',pos:[-6,-3],color:[1,.6,.2],size:9},{name:'B',type:'Free',pos:[-5,3],color:[1,.6,.2],size:9},{name:'C',type:'Free',pos:[6,-3],color:[1,.6,.2],size:9},{name:'D',type:'Free',pos:[5,3],color:[1,.6,.2],size:9}],init:'',draw:'n=90;forall(1..n,k,t=k/n;p=A.xy*t+B.xy*(1-t);q=C.xy*t+D.xy*(1-t);draw(p,q,color->hue(t*.7+.45),alpha->.65,size->1));draw(A,B,color->(.9,.9,.9),size->2);draw(C,D,color->(.9,.9,.9),size->2);'},
triangle:{rect:[-8,-5,8,5],geometry:[{name:'A',type:'Free',pos:[-3,-2],color:[1,.6,.2],size:9},{name:'B',type:'Free',pos:[3,-2],color:[1,.6,.2],size:9},{name:'C',type:'Free',pos:[0,3],color:[1,.6,.2],size:9},{name:'a',type:'Segment',args:['B','C'],color:[.3,.8,1]},{name:'b',type:'Segment',args:['A','C'],color:[.3,.8,1]},{name:'c',type:'Segment',args:['A','B'],color:[.3,.8,1]},{name:'circle',type:'CircleBy3',args:['A','B','C'],color:[.3,.8,1]}],init:'',draw:'O=meet(perp(join(A,B),(A.xy+B.xy)/2),perp(join(A,C),(A.xy+C.xy)/2));G=(A.xy+B.xy+C.xy)/3;draw(O,color->(.3,.8,1),size->6);draw(G,color->(1,.7,.3),size->6);draw(O,G,color->(.8,.7,1));drawtext([-7,-4],"周长 "+format(|A.xy-B.xy|+|B.xy-C.xy|+|C.xy-A.xy|,2),color->(.8,.85,.9),size->14);'}};
function load(m){if(cdy)cdy.shutdown();mode=m;document.getElementById('scene').innerHTML='';var s=scenes[m];cdy=CindyJS({ports:[{id:'scene',width:480,height:272,background:'#101722',transform:[{visibleRect:s.rect}]}],geometry:s.geometry,scripts:{init:s.init,draw:s.draw},use:m==='julia'?['CindyGL']:[],animation:{autoplay:false},defaultAppearance:{pointSize:8,lineSize:2}});window.atomMath={mode:m,engine:!!cdy};document.getElementById('hint').textContent=m==='julia'?'拖动橙色点，改变分形':m==='rays'?'拖动四个端点，直线生出曲线':'拖动顶点，观察外接圆与重心';document.querySelectorAll('[data-mode]').forEach(function(b){b.classList.toggle('active',b.dataset.mode===m)})}
document.querySelectorAll('[data-mode]').forEach(function(b){b.onclick=function(){load(b.dataset.mode)}});document.getElementById('reset').onclick=function(){load(mode)};load(mode);
''')
finish(p,'数学游乐场','CindyJS · 可拖动分形、光线包络与三角几何','<path d="M12 46 32 12 52 46Z"/><circle cx="32" cy="32" r="21"/><circle cx="32" cy="32" r="3"/><path d="M12 46 32 32 52 46M32 12v20"/>')
p=ROOT/'ports/circuit-lab';p.mkdir(exist_ok=True)
bootstrap=p/'circuitjs1/circuitjs1.nocache.js'
s=bootstrap.read_text();a=s.index('  function setupInstallLocation(){');b=s.index('\n  function installScript',a);bootstrap.write_text(s[:a]+'  function setupInstallLocation(){frameDoc=$doc_0;}\n'+s[b:])
for f in (p/'circuitjs1').glob('*.cache.js'):
 s=f.read_text().replace('var $wnd = $wnd || window.parent;','var $wnd = window;');s=s.replace("height = height - (this$static.hideMenu?0:30);","height = height - (this$static.hideMenu?84:30);");f.write_text(s)
(p/'index.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><meta name="gwt:property" content="locale=en_UK"><title>电路实验室</title><link rel="stylesheet" href="font/fontello.css"><style>html,body{height:100%;margin:0!important;overflow:hidden;font:13px sans-serif;background:var(--bg);color:var(--ink)}canvas{position:relative;top:28px}.head{position:fixed;top:6px;left:12px;right:12px;display:flex;justify-content:space-between;z-index:100}.atomtools{position:fixed;bottom:8px;left:10px;right:10px;display:flex;gap:6px;z-index:100}.atomtools button,.atomtools select{height:40px;font:13px sans-serif;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:8px;flex:1}.atomtools select{flex:1.8;min-width:0}.gwt-DialogBox{max-width:440px!important;max-height:310px!important;overflow:auto;background:var(--card)!important;color:var(--ink)!important}.gwt-DialogBox input{max-width:100px}.gwt-MenuItem{font-size:12px}.gwt-Frame{border:0}.offScreen{position:absolute;right:101%;overflow:hidden}#status{font-size:11px;color:var(--muted)}#error{position:fixed;inset:40px 20px 70px;background:var(--card);padding:20px;z-index:101;display:none}</style><script>window.atomSearch='?hideMenu=true&hideSidebar=true&hideInfoBox=true&running=true&editable=true&startCircuit=lrc.txt&lang=en';window.oncircuitjsloaded=function(sim){window.atomCircuitLoaded(sim)};</script><script src="lz-string.min.js"></script><script src="main.js"></script></head><body><div class="head"><span>电路实验室</span><span id="status">正在初始化求解器…</span></div><div class="atomtools"><select id="preset" aria-label="实验电路"><option value="lrc">RLC振荡</option><option value="rectifier">半波整流</option><option value="timer">555振荡器</option></select><button id="pause">暂停</button><button id="change">参数×1</button><button id="reset">重置</button></div><div id="error"></div><script src="circuitjs1/circuitjs1.nocache.js"></script></body></html>''')
(p/'main.js').write_text('''var sim,presets,scale=1,current='lrc';fetch('presets.json').then(function(r){return r.json()}).then(function(d){presets=d;if(sim)load()}).catch(function(e){error(e.message)});function error(s){var e=document.getElementById('error');e.style.display='block';e.textContent=s}function load(){if(!sim||!presets)return;var text=presets[current];if(scale===2){text=text.split('\\n').map(function(l){var a=l.split(' ');if(a[0]==='r'){a[6]=String(Number(a[6])*2);return a.join(' ')}return l}).join('\\n')}sim.importCircuit(text,false);sim.setSimRunning(true);document.getElementById('pause').textContent='暂停';document.getElementById('change').textContent='电阻×'+scale;window.atomCircuit={ready:true,preset:current,scale:scale};}window.atomCircuitLoaded=function(s){sim=s;sim.onupdate=function(){var t=sim.getTime(),elm=sim.getElements().find(function(e){return e.getType()==='ResistorElm'});var msg='t '+t.toFixed(4)+'s';if(elm)msg+=' · '+(elm.getCurrent()*1000).toFixed(2)+'mA';document.getElementById('status').textContent=msg};load()};window.addEventListener('DOMContentLoaded',function(){document.getElementById('preset').onchange=function(){current=this.value;scale=1;load()};document.getElementById('pause').onclick=function(){if(sim){sim.setSimRunning(!sim.isRunning());this.textContent=sim.isRunning()?'暂停':'继续'}};document.getElementById('change').onclick=function(){scale=scale===1?2:1;load()};document.getElementById('reset').onclick=function(){scale=1;load()}});setTimeout(function(){if(!sim)error('电路引擎尚未就绪，请返回桌面后重新打开。')},15000);
''')
finish(p,'电路实验室','CircuitJS1 · RLC、整流与555真实电路仿真','<path d="M8 24h10l3-6 6 12 6-12 6 12 3-6h14M8 24v24h18m12 0h18V24M26 39v18m12-18v18"/>')
