# -*- coding: utf-8 -*-
"""Rebuild a small-screen dot display around skeeto's original GPU Life engine."""
from pathlib import Path
import shutil,json
ROOT=Path(__file__).resolve().parents[1];src=ROOT/'vendor/dot-life-src';p=ROOT/'ports/dot-life';p.mkdir(exist_ok=True)
shutil.copytree(src/'glsl',p/'glsl',dirs_exist_ok=True);shutil.copytree(src/'lib',p/'lib',dirs_exist_ok=True);shutil.copy(src/'UNLICENSE',p/'UNLICENSE');shutil.copytree(src/'js',p/'upstream-source',dirs_exist_ok=True)
s=(src/'js/gol.js').read_text();s=s[:s.index('/* Initialize everything. */')];s=s.replace("$('.fps').text(this.fps + ' FPS');","// UI reports generations instead of a fixed selector.")
(p/'gol.js').write_text(s)
(p/'glsl/copy.frag').write_text('''precision mediump float;uniform sampler2D state;uniform vec2 scale;void main(){vec2 uv=gl_FragCoord.xy/scale;float live=texture2D(state,uv).r;vec2 q=fract(gl_FragCoord.xy/8.0)-.5;float d=length(q);float core=1.0-smoothstep(.22,.35,d);float halo=exp(-d*d*12.0)*.22;vec3 dark=vec3(.025,.045,.05);vec3 ink=vec3(.25,1.0,.68);gl_FragColor=vec4(dark+ink*(core*(.05+live*.75)+halo*live),1.0);}''')
(p/'index.html').write_text('''<!doctype html><html lang="zh"><head><meta charset="utf-8"><title>点阵生命</title><style>*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden;font:13px sans-serif;background:var(--bg);color:var(--ink)}.head{position:absolute;top:9px;left:12px;right:12px;display:flex;justify-content:space-between}#world{position:absolute;top:52px;left:0;width:100%;height:240px;touch-action:none}#hint{position:absolute;top:33px;left:18px;font-size:11px;color:var(--muted)}.atomtools{position:absolute;bottom:10px;left:10px;right:10px;display:flex;gap:6px}.atomtools button,.atomtools select{height:40px;min-width:0;flex:1;border:1px solid var(--line);border-radius:7px;background:var(--card);color:var(--ink);font:12px sans-serif}.atomtools select{flex:1.5}</style></head><body><div class="head"><span>点阵生命</span><span id="status">GPU · 64×32</span></div><div id="hint">拖动播种 · 右键擦除 · Conway生命规则</div><canvas id="world" width="512" height="256"></canvas><div class="atomtools"><select id="preset" aria-label="生命图样"><option value="gun">滑翔机枪</option><option value="pulsar">脉冲星</option><option value="ships">飞船编队</option><option value="random">随机宇宙</option></select><button id="play">暂停</button><button id="step">单步</button><button id="speed">12代/秒</button><button id="clear">清空</button></div><script crossorigin="anonymous" src="lib/igloo-0.1.0.js"></script><script crossorigin="anonymous" src="gol.js"></script><script src="main.js"></script></body></html>''')
(p/'main.js').write_text('''(function(){try{var c=document.getElementById('world'),life=new GOL(c,8),playing=true,generation=0,last=0,hz=12,drag=false,erase=false,lastCell=null;window.dotLife={engine:life,get generation(){return generation},get playing(){return playing}};
function cell(x,y){if(x>=0&&x<64&&y>=0&&y<32)life.poke(x,y,1)}function pattern(kind){life.setEmpty();generation=0;if(kind==='random'){life.setRandom(.25)}else if(kind==='gun'){var pts=[[24,0],[22,1],[24,1],[12,2],[13,2],[20,2],[21,2],[34,2],[35,2],[11,3],[15,3],[20,3],[21,3],[34,3],[35,3],[0,4],[1,4],[10,4],[16,4],[20,4],[21,4],[0,5],[1,5],[10,5],[14,5],[16,5],[17,5],[22,5],[24,5],[10,6],[16,6],[24,6],[11,7],[15,7],[12,8],[13,8]];pts.forEach(function(q){cell(q[0]+12,q[1]+11)})}else if(kind==='pulsar'){var pts=[];[2,3,4,8,9,10].forEach(function(v){[0,5,7,12].forEach(function(w){pts.push([v,w],[w,v])})});pts.forEach(function(q){cell(q[0]+25,q[1]+9)})}else{var ship=[[1,0],[4,0],[0,1],[0,2],[4,2],[0,3],[1,3],[2,3],[3,3]];[6,14,22].forEach(function(y){ship.forEach(function(q){cell(q[0]+15,q[1]+y)})})}life.draw();update()}
function update(){var count=life.get().reduce(function(a,b){return a+b},0);document.getElementById('status').textContent=generation+'代 · '+count+'个生命';life.draw()}
function paint(e){var r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*64/r.width),y=31-Math.floor((e.clientY-r.top)*32/r.height);if(x<0||x>63||y<0||y>31)return;if(lastCell){let dx=x-lastCell[0],dy=y-lastCell[1],n=Math.max(Math.abs(dx),Math.abs(dy),1);for(let i=0;i<=n;i++)life.poke(Math.round(lastCell[0]+dx*i/n),Math.round(lastCell[1]+dy*i/n),!erase)}else life.poke(x,y,!erase);lastCell=[x,y];update()}
c.onpointerdown=function(e){drag=true;erase=e.button===2;lastCell=null;c.setPointerCapture(e.pointerId);paint(e)};c.onpointermove=function(e){if(drag)paint(e)};c.onpointerup=c.onpointercancel=function(){drag=false;lastCell=null};c.oncontextmenu=function(e){e.preventDefault()};document.getElementById('preset').onchange=function(){pattern(this.value)};document.getElementById('play').onclick=function(){playing=!playing;this.textContent=playing?'暂停':'继续'};document.getElementById('step').onclick=function(){playing=false;document.getElementById('play').textContent='继续';life.step();generation++;update()};document.getElementById('clear').onclick=function(){life.setEmpty();generation=0;update()};document.getElementById('speed').onclick=function(){hz=hz===12?24:hz===24?6:12;this.textContent=hz+'代/秒'};function tick(t){if(playing&&!drag&&t-last>=1000/hz){life.step();generation++;life.draw();last=t;if(generation%6===0)update()}requestAnimationFrame(tick)}pattern('gun');requestAnimationFrame(tick);window.addEventListener('pagehide',function(){playing=false})}catch(e){document.getElementById('status').textContent='引擎失败：'+e.message}})();''')
icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.4"><circle cx="20" cy="20" r="4"/><circle cx="32" cy="20" r="4"/><circle cx="44" cy="20" r="4"/><circle cx="20" cy="32" r="4"/><circle cx="44" cy="32" r="4"/><circle cx="20" cy="44" r="4"/><circle cx="32" cy="44" r="4"/><circle cx="44" cy="44" r="4"/></svg>'
(p/'icon.svg').write_text(icon);(p/'bundle.json').write_text(json.dumps({'manifest':{'id':p.name,'name':'点阵生命','description':'原版GPU生命游戏 · 点阵播种与演化','entry':'index.html','icon':'icon.svg','theme_ui':'controls','layout':'fullscreen'},'files':{'index.html':(p/'index.html').read_text(),'icon.svg':icon}},ensure_ascii=False,indent=2))
(p/'UPSTREAM.txt').write_text('https://github.com/skeeto/webgl-game-of-life\nSHA '+(src/'ATOM_SHA').read_text()+'\nUnlicense; original GPU step shader retained. ATOM replaces UI and display fragment with circular LED dots.\n')
