from pathlib import Path
import shutil,re,json,subprocess
root=Path('atom/ports');vendor=Path('atom/vendor')
style='''html,body{margin:0;height:100%;overflow:hidden;font:14px sans-serif}canvas{display:block}.atomtools{position:fixed;bottom:10px;left:12px;right:12px;display:flex;gap:6px;z-index:100}.atomtools button{height:40px;flex:1;border:1px solid #ffffff66;background:#14202de8;color:white;border-radius:8px;font:13px sans-serif}.atomtitle{position:fixed;left:14px;top:12px;z-index:100;font:13px sans-serif;color:white;pointer-events:none;text-shadow:0 1px 4px #000}'''
def copy(src,id):
 p=root/id;shutil.copytree(vendor/src,p,ignore=shutil.ignore_patterns('.git'),dirs_exist_ok=True);return p
def finish(p,name,repo,src):
 h=(p/'index.html').read_text();h=h.replace('<head>','<head><script>var NativeImage=Image;window.Image=function(w,h){var i=new NativeImage(w,h);i.crossOrigin="anonymous";return i};Image.prototype=NativeImage.prototype;</script>')
 h=h.replace('<script src=','<script crossorigin="anonymous" src=');(p/'index.html').write_text(h)
 (p/'bundle.json').write_text(json.dumps(dict(manifest=dict(id=p.name,name=name,description=name+' · 实时交互',entry='index.html',layout='fullscreen'),files={'index.html':h}),ensure_ascii=False))
 (p/'UPSTREAM.txt').write_text('https://github.com/'+repo+'\n'+subprocess.check_output(['git','-C',str(vendor/src),'rev-parse','HEAD']).decode())
p=copy('flow','volume-flow');shutil.copy('atom/tools/webgl2-compat.js',p/'webgl2-compat.js')
s=(p/'shared.js').read_text();a=s.index('var QUALITY_LEVELS =');b=s.index('var LIGHT_DIRECTION',a)
s=s[:a]+'''var QUALITY_LEVELS=[{resolution:[64,64],diameter:.065,alpha:.7},{resolution:[128,64],diameter:.05,alpha:.6},{resolution:[128,128],diameter:.04,alpha:.5}];var OPACITY_TEXTURE_RESOLUTION=256;\n'''+s[b:];s=s.replace('var SLICES = 128','var SLICES = 32').replace('var SORT_PASSES_PER_FRAME = 50','var SORT_PASSES_PER_FRAME = 12');(p/'shared.js').write_text(s)
(p/'main.js').write_text('''var flow=new Flow(document.getElementById('render'));flow.setHue(.56);flow.setTimeScale(2);flow.setPersistence(.25);var level=0,hue=.56,speed=2;document.getElementById('quality').onclick=function(){level=(level+1)%3;flow.changeQualityLevel(level);this.textContent=['4千粒子','8千粒子','1.6万粒子'][level]};document.getElementById('color').onclick=function(){hue=(hue+.18)%1;flow.setHue(hue)};document.getElementById('speed').onclick=function(){speed=speed===2?0:2;flow.setTimeScale(speed);this.textContent=speed?'暂停':'继续'};document.getElementById('curl').onclick=function(){var n=Math.random()*.7+.1;flow.setPersistence(n)};''')
(p/'index.html').write_text('<!doctype html><html><head><meta charset="utf-8"><script src="webgl2-compat.js"></script><style>'+style+'body{background:#e6e6e6}#render{position:absolute;inset:0}.atomtitle{color:#24334b;text-shadow:none}</style></head><body><canvas id="render"></canvas><div class="atomtitle">体积流场 · 拖动旋转 · 滚轮缩放</div><div class="atomtools"><button id="quality">4千粒子</button><button id="color">换色</button><button id="curl">变换流场</button><button id="speed">暂停</button></div><script src="shared.js"></script><script src="flow.js"></script><script src="main.js"></script></body></html>')
finish(p,'体积流场','dli/flow','flow')
p=root/'living-pattern';shutil.copytree(vendor/'reaction/docs',p,dirs_exist_ok=True);shutil.copy(vendor/'reaction/LICENSE',p/'LICENSE')
h=(p/'index.html').read_text();h=h.replace('id="map-tabs-id-uniform-id" />','id="map-tabs-id-uniform-id" checked />').replace('id="map-tabs-id-image-id" checked','id="map-tabs-id-image-id"')
extra='''<style>'''+style+'''header,footer,.intro,.controls-block,#canvas-buttons-column,#indicators{display:none!important}main,.demo,#canvas-container{position:fixed!important;inset:0!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;max-width:none!important}#canvas{width:100%!important;height:100%!important}.atomtitle{color:#eee}</style><div class="atomtitle">生命纹理 · 拖动播种</div><div class="atomtools"><button id="atomPreset">纹理：波纹</button><button id="atomPause">暂停</button><button id="atomReset">重新生长</button></div><script>window.addEventListener('load',function(){var preset=0,speed=20;Page.Range.setValue('speed-range-id',20);document.getElementById('atomPreset').onclick=function(){preset=(preset+1)%6;var e=document.querySelector('#presets-fixed-select-id [data-value="'+preset+'"].select-value');e.click();Page.Range.setValue('speed-range-id',20);speed=20;document.getElementById('atomPause').textContent='暂停';document.getElementById('reset-button-id').click();this.textContent='纹理：'+['波纹','线条','交错','微光','几何','孔洞'][preset]};document.getElementById('atomPause').onclick=function(){speed=speed?0:20;Page.Range.setValue('speed-range-id',speed);this.textContent=speed?'暂停':'继续'};document.getElementById('atomReset').onclick=function(){document.getElementById('reset-button-id').click()};});</script>'''
h=h.replace('</body>',extra+'</body>');(p/'index.html').write_text(h)
pf=p/'script/page.min.js';s=pf.read_text();s=s.replace('window.history.replaceState("","",','window.atomReplaceState("","",');pf.write_text(s)
h=(p/'index.html').read_text().replace('<head>','<head><script>window.atomReplaceState=function(){try{history.replaceState.apply(history,arguments)}catch(e){}}</script>');(p/'index.html').write_text(h)
finish(p,'生命纹理','piellardj/reaction-diffusion-webgl','reaction')
p=copy('ocean','moon-ocean');shutil.copy('atom/tools/webgl2-compat.js',p/'webgl2-compat.js')
s=(p/'js/demo.js').read_text(encoding='utf-8-sig');s=s.replace('var res = 512;','var res = 128;').replace('var gres = 256;','var gres = 64;').replace('new CloudShader( this.ms_Renderer, 512 )','new CloudShader( this.ms_Renderer, 128 )').replace('this.ms_soundWaves.play();','// Sound starts only after a user gesture.').replace('this.ms_soundRain.play();','// Sound optional.').replace('this.ms_ImageLoader = new THREE.ImageLoader( this.ms_Loader );','this.ms_ImageLoader = new THREE.ImageLoader( this.ms_Loader );this.ms_ImageLoader.crossOrigin="anonymous";').replace('this.InitGui();','// ATOM controls replace dat.GUI.').replace('$( document ).keydown( keyHandler( true ) );',"document.addEventListener('keydown',keyHandler(true));").replace('$( document ).keyup( keyHandler( false ) );',"document.addEventListener('keyup',keyHandler(false));").replace('messg( message, type, timeout );','// No loading toast over the scene.')
# Remove optional large ship model loading, retaining the camera and ship group.
a=s.index('\t\tvar loader = new THREE.OBJMTLLoader');b=s.index('\n\t\t// Add rain',a);s=s[:a]+'\t\tthis.ms_BlackPearl = null;\n'+s[b:]
(p/'js/demo.js').write_text(s)
h=(p/'index.html').read_text(encoding='utf-8-sig').replace('<head>','<head><script src="webgl2-compat.js"></script>')
extra='''<style>'''+style+'''#env-selector,.dg,.messg{display:none!important}canvas{width:100%;height:100%}</style><div class="atomtitle">月光海洋 · 拖动环视 · 滚轮靠近</div><div class="atomtools"><button onclick="DEMO.UpdateEnvironment('night')">月夜</button><button onclick="DEMO.UpdateEnvironment('day')">白昼</button><button onclick="DEMO.UpdateEnvironment('sunset')">日落</button><button onclick="DEMO.ms_Ocean.windX=DEMO.ms_Ocean.windX===10?25:10;DEMO.ms_Ocean.changed=true">风力</button></div>'''
h=h.replace('<script src="js/libs/jquery-2.1.4.min.js"></script>','');h=h.replace('</body>',extra+'</body>');(p/'index.html').write_text(h);finish(p,'月光海洋','jbouny/fft-ocean','ocean')
