Section "Device"
 Identifier "Rockchip Graphics"
 Driver "modesetting"
 Option "AccelMethod" "glamor"
 Option "DRI" "2"
 Option "FlipFB" "none"
 Option "NoEDID" "true"
 Option "SWcursor" "true"
EndSection
Section "Screen"
 Identifier "Default Screen"
 Device "Rockchip Graphics"
 DefaultDepth 24
EndSection
