(function(){'use strict';var canvas=document.getElementById('scene'),message=document.getElementById('message'),context,visualizer,master,fileSource,buffer,playing=false,mode='demo',preset=0,automatic=false,lastPreset=0,lastFrame=0,nextBeat=0,beat=0,timer=null;var pack=window.butterchurnPresetsMinimal,engine=window.butterchurn,keys,presets;function say(s){message.textContent=s;}function setup(){try{var A=window.AudioContext||window.webkitAudioContext;context=new A();master=context.createGain();master.gain.value=.35;master.connect(context.destination);presets=pack.getPresets();keys=Object.keys(presets);if(!keys.length)throw Error('预设包为空');visualizer=engine.default.createVisualizer(context,canvas,{width:480,height:360,pixelRatio:1,meshWidth:24,meshHeight:18,textureRatio:1});visualizer.connectAudio(master);change(0,false);say('点击播放节拍，或选择本地音乐');window.musicVision={engine:'Butterchurn 2.6.7',presetCount:keys.length,get visualizer(){return visualizer;},get audioContext(){return context;}};requestAnimationFrame(frame);}catch(e){say('视觉引擎不可用：'+e.message);document.getElementById('play').disabled=true;document.getElementById('choose').disabled=true;document.getElementById('next').disabled=true;document.getElementById('auto').disabled=true;}}
function change(index,blend){preset=(index+keys.length)%keys.length;visualizer.loadPreset(presets[keys[preset]],blend?1.5:0);document.getElementById('preset-name').textContent=keys[preset];lastPreset=performance.now();}
function tone(at,freq,length,type,gain){var o=context.createOscillator(),g=context.createGain();o.type=type||'sine';o.frequency.setValueAtTime(freq,at);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(gain,at+.005);g.gain.exponentialRampToValueAtTime(.0001,at+length);o.connect(g);g.connect(master);o.start(at);o.stop(at+length+.02);o.onended=function(){o.disconnect();g.disconnect();};}
function drum(at){var o=context.createOscillator(),g=context.createGain();o.frequency.setValueAtTime(150,at);o.frequency.exponentialRampToValueAtTime(45,at+.16);g.gain.setValueAtTime(.9,at);g.gain.exponentialRampToValueAtTime(.001,at+.22);o.connect(g);g.connect(master);o.start(at);o.stop(at+.24);o.onended=function(){o.disconnect();g.disconnect();};}
function schedule(){if(!playing||mode!=='demo')return;while(nextBeat<context.currentTime+.12){if(beat%4===0)drum(nextBeat);tone(nextBeat,[130.81,164.81,196,261.63][Math.floor(beat/4)%4],.16,'triangle',beat%2?.1:.24);if(beat%2===0)tone(nextBeat,2200,.026,'square',.05);nextBeat+=.125;beat++;}}
function stop(){playing=false;if(timer){clearInterval(timer);timer=null;}if(fileSource){try{fileSource.stop();}catch(e){}fileSource.disconnect();fileSource=null;}document.getElementById('play').textContent=mode==='file'?'播放音乐':'播放节拍';master.gain.setValueAtTime(0,context.currentTime);}
function start(){context.resume().then(function(){playing=true;master.gain.setValueAtTime(.35,context.currentTime);if(mode==='file'&&buffer){fileSource=context.createBufferSource();fileSource.buffer=buffer;fileSource.loop=true;fileSource.connect(master);fileSource.start();}else{mode='demo';beat=0;nextBeat=context.currentTime+.03;schedule();timer=setInterval(schedule,25);}document.getElementById('play').textContent='暂停';say('');}).catch(function(e){say('音频启动失败：'+e.message);});}
function frame(t){if(visualizer&&t-lastFrame>32){try{visualizer.render();}catch(e){say('渲染失败：'+e.message);return;}lastFrame=t;if(automatic&&t-lastPreset>18000)change(preset+1,true);}requestAnimationFrame(frame);}
document.getElementById('play').onclick=function(){if(!visualizer)return;if(playing)stop();else start();};document.getElementById('next').onclick=function(){if(visualizer)change(preset+1,true);};document.getElementById('auto').onclick=function(){automatic=!automatic;this.textContent='自动：'+(automatic?'开':'关');this.classList.toggle('active',automatic);};document.getElementById('choose').onclick=function(){document.getElementById('audio-file').click();};document.getElementById('audio-file').onchange=function(){var file=this.files[0];if(!file)return;if(file.size>40*1024*1024){say('请选择小于 40 MiB 的音乐文件');return;}stop();say('正在读取 '+file.name);file.arrayBuffer().then(function(a){return context.decodeAudioData(a);}).then(function(b){buffer=b;mode='file';document.getElementById('play').textContent='播放音乐';say('已载入 '+file.name+'，点击播放');}).catch(function(e){say('文件解码失败：'+e.message);});};document.addEventListener('visibilitychange',function(){if(document.hidden&&context)stop();});window.addEventListener('pagehide',function(){if(context){stop();context.close();}});setup();})();
