// Baked pose frames. GENERATED by scripts/import-frames.js from painted PNGs;
// safe to regenerate at any time, and safe to leave empty (this is the default).
//
// Everything the pet does is composed procedurally from grid primitives, which is
// what makes one pose cover 28 coats. This file is the escape hatch: drop a hand
// drawn or generated frame in here and it wins over the composer for that pose,
// for the coats you name, and nothing else changes.
//
// Shape:
//   ART_FRAMES[species][pose][key] = { COLS, ROWS, rows: ['..CC..', ...] }
//
// `key` is looked up in this order, so you can be as specific as you like:
//   1. a coat name exactly as it appears in PATTERNS  ('Orange Tabby')
//   2. a build name from PATTERN_BUILD                ('slender', 'retriever')
//   3. '*'                                            every coat of that species
// Anything with no match falls back to the composer, so a half finished pack still
// runs. `rows` holds one ROLE letter per cell (C K W X I N E O, '.' for empty), not
// colours: the palette is applied per coat at draw time.
//
// Do NOT bake the halo ('H'). buildSprite runs outlineHalo() over whatever lands
// here, which fills any gap in the outline and grows the halo, exactly as it does
// for a composed pose.
//
// Only the five HELD poses are read: sit, type, loaf, rear, hunt. The other six
// activities (groom, ponder, play, bat) are animation rigs whose
// limbs move with a quantised parameter, so a single still would freeze them. See
// docs/frame-pack.md.
const ART_FRAMES = {
  cat: {},
  dog: {},
};

if (typeof module !== 'undefined' && module.exports) module.exports = { ART_FRAMES };
else if (typeof window !== 'undefined') window.ART_FRAMES = ART_FRAMES;
